# Generated by Django 5.1.6 on 2025-04-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Used in the URL, e.g., /featured/<slug>', unique=True)),
                ('description_top', models.TextField(blank=True, null=True)),
                ('description_bottom', models.TextField(blank=True, null=True)),
                ('api_route', models.CharField(help_text='Relative API path. E.g., /consultancy/?destination=canada', max_length=500)),
                ('priority', models.PositiveIntegerField(default=999, help_text='Lower = higher priority')),
                ('is_active', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_author', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
