# Generated by Django 5.1.6 on 2025-04-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured', '0002_featuredpage_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredpage',
            name='main_title',
            field=models.CharField(blank=True, help_text='Displayed as <h1> on the page', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='featuredpage',
            name='sub_title',
            field=models.CharField(blank=True, help_text='Displayed as <h2> below top description', max_length=255, null=True),
        ),
    ]
