# Generated by Django 5.1.6 on 2025-03-07 03:37

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('country_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('cover_page', models.ImageField(blank=True, null=True, upload_to='cover_pages/')),
                ('why_choose', tinymce.models.HTMLField(blank=True, null=True)),
                ('requirements', tinymce.models.HTMLField(blank=True, null=True)),
                ('documents_required', tinymce.models.HTMLField(blank=True, null=True)),
                ('scholarships', tinymce.models.HTMLField(blank=True, null=True)),
                ('more_information', tinymce.models.HTMLField(blank=True, null=True)),
                ('faqs', tinymce.models.HTMLField(blank=True, null=True)),
                ('other_destinations', tinymce.models.HTMLField(blank=True, null=True)),
                ('courses_to_study', models.ManyToManyField(blank=True, related_name='destinations', to='course.course')),
                ('universities', models.ManyToManyField(blank=True, related_name='destinations', to='university.university')),
            ],
        ),
    ]
