# Generated by Django 5.1.6 on 2025-04-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='ept_requirement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='gpa_requirement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
