# Generated by Django 5.1.6 on 2025-03-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0002_consultancy_partner_universities_and_more'),
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='consultancies',
            field=models.ManyToManyField(blank=True, related_name='destination_consultancies', to='consultancy.consultancy'),
        ),
    ]
