# Generated by Django 5.1.6 on 2025-03-13 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_destination_consultancies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='other_destinations',
        ),
    ]
