# Generated by Django 5.1.6 on 2025-03-07 03:33

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Exam Name', max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='exams/icons/')),
                ('short_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('exam_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type', models.CharField(choices=[('physical', 'Physical'), ('online', 'Online'), ('hybrid', 'Hybrid')], max_length=50)),
                ('exam_centers', tinymce.models.HTMLField(blank=True, null=True)),
                ('about', tinymce.models.HTMLField(blank=True, null=True)),
                ('similar_exams', models.ManyToManyField(blank=True, to='exam.exam')),
            ],
        ),
    ]
