# Generated by Django 5.1.6 on 2025-03-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0002_consultancy_partner_universities_and_more'),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='preparation_classes',
            field=models.ManyToManyField(blank=True, related_name='exams_preparation', to='consultancy.consultancy'),
        ),
    ]
