# Generated by Django 5.1.6 on 2025-03-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exam_preparation_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='type',
            field=models.CharField(choices=[('english_proficiency', 'English Proficiency Test'), ('standardized_test', 'Standardized Test')], max_length=50),
        ),
    ]
