# Generated by Django 5.1.6 on 2025-03-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0001_initial'),
        ('destination', '0001_initial'),
        ('exam', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancy',
            name='partner_universities',
            field=models.ManyToManyField(blank=True, related_name='consultancies', to='university.university'),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='study_abroad_destinations',
            field=models.ManyToManyField(blank=True, related_name='consultancy_destinations', to='destination.destination'),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='test_preparation',
            field=models.ManyToManyField(blank=True, related_name='consultancies', to='exam.exam'),
        ),
    ]
