# Generated by Django 5.1.6 on 2025-03-05 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultancy', '0001_initial'),
        ('core', '0001_initial'),
        ('destination', '__first__'),
        ('exam', '__first__'),
        ('university', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancy',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.district'),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='partner_universities',
            field=models.ManyToManyField(blank=True, related_name='consultancies', to='university.university'),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='study_abroad_destinations',
            field=models.ManyToManyField(blank=True, related_name='destination_consultancies', to='destination.destination'),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='test_preparation',
            field=models.ManyToManyField(blank=True, related_name='consultancies', to='exam.exam'),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultancygallery',
            name='consultancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='consultancy.consultancy'),
        ),
    ]
