# Generated by Django 5.1.6 on 2025-03-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultancy', '0001_initial'),
        ('core', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancy',
            name='districts',
            field=models.ManyToManyField(blank=True, to='core.district'),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='partner_universities',
            field=models.ManyToManyField(blank=True, related_name='consultancies', to='university.university'),
        ),
    ]
