# Generated by Django 5.1.6 on 2025-03-26 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultancy', '0002_initial'),
        ('destination', '0001_initial'),
        ('exam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancy',
            name='study_abroad_destinations',
            field=models.ManyToManyField(blank=True, related_name='consultancy_destinations', to='destination.destination'),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='test_preparation',
            field=models.ManyToManyField(blank=True, related_name='consultancies', to='exam.exam'),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultancybranch',
            name='consultancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='consultancy.consultancy'),
        ),
        migrations.AddField(
            model_name='consultancygallery',
            name='consultancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='consultancy.consultancy'),
        ),
    ]
