# Generated by Django 5.1.6 on 2025-03-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0002_initial'),
        ('destination', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultancy',
            name='study_abroad_destinations',
            field=models.ManyToManyField(blank=True, related_name='consultancy_destinations', to='destination.destination'),
        ),
    ]
