# Generated by Django 5.1.6 on 2025-03-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0002_consultancy_partner_universities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultancy',
            name='priority',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Lower the number, higher the priority', null=True),
        ),
    ]
