# Generated by Django 5.1.6 on 2025-03-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0003_alter_consultancy_study_abroad_destinations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultancy',
            name='district',
        ),
    ]
