# Generated by Django 5.1.5 on 2025-03-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0003_alter_consultancy_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultancy',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
