# Generated by Django 5.1.6 on 2025-03-06 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0004_remove_consultancy_district'),
        ('core', '0004_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancy',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.district'),
        ),
    ]
