# Generated by Django 5.1.6 on 2025-03-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0005_consultancy_district'),
        ('core', '0004_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultancy',
            name='district',
        ),
        migrations.AddField(
            model_name='consultancy',
            name='districts',
            field=models.ManyToManyField(blank=True, to='core.district'),
        ),
    ]
