# Generated by Django 5.1.6 on 2025-03-06 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0006_remove_consultancy_district_consultancy_districts'),
        ('core', '0005_verifieditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancy',
            name='verified',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.verifieditem'),
        ),
    ]
