# Generated by Django 5.1.6 on 2025-03-06 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0007_consultancy_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultancy',
            name='branches',
        ),
        migrations.AddField(
            model_name='consultancy',
            name='google_map_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='has_branches',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='priority',
            field=models.PositiveIntegerField(default=1, help_text='Lower the number, higher the priority'),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='services',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConsultancyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('consultancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='consultancy.consultancy')),
            ],
        ),
    ]
