# Generated by Django 5.1.6 on 2025-03-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0008_remove_consultancy_branches_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultancy',
            name='partner_universities',
        ),
        migrations.RemoveField(
            model_name='consultancy',
            name='study_abroad_destinations',
        ),
        migrations.RemoveField(
            model_name='consultancy',
            name='test_preparation',
        ),
    ]
