# Generated by Django 5.1.6 on 2025-03-06 15:49

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0010_consultancy_partner_universities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultancy',
            name='services',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
