# Generated by Django 5.1.6 on 2025-03-07 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultancy', '0002_consultancy_partner_universities_and_more'),
        ('university', '0002_university_consultancies_to_apply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('consultancy', 'Consultancy'), ('university', 'University'), ('course', 'Course'), ('exam', 'Exam'), ('destination', 'Destination'), ('event', 'Event')], max_length=20)),
                ('entity_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='consultancy.consultancy')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='university.university')),
            ],
        ),
    ]
