# Generated by Django 5.1.5 on 2025-03-31 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='college.college'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='entity_type',
            field=models.CharField(choices=[('university', 'University'), ('consultancy', 'Consultancy'), ('college', 'College'), ('destination', 'Destination'), ('exam', 'Exam'), ('event', 'Event'), ('course', 'Course')], max_length=20),
        ),
    ]
