# Generated by Django 5.1.5 on 2025-03-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('consultancy', 'Consultancy'), ('university', 'University'), ('college', 'College'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
