# Generated by Django 5.1.6 on 2025-03-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('course', '0002_alter_course_options_alter_course_duration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseDuration',
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
