# Generated by Django 5.1.6 on 2025-03-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0004_remove_consultancy_district'),
        ('core', '0002_delete_courseduration_alter_district_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='District',
        ),
    ]
