# Generated by Django 5.1.6 on 2025-03-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ad title for internal reference', max_length=255)),
                ('placement', models.CharField(choices=[('exclusive_below_navbar', 'Exclusive Ad Below Navbar'), ('exclusive_above_footer', 'Exclusive Ad Above Footer'), ('below_navbar_blog_news', 'Below Navbar Blog and News'), ('above_headline_blog_news', 'Above Headline Blog and News'), ('below_headline_blog_news', 'Below Headline Blog and News'), ('below_featured_image_blog_news', 'Below Featured Image Blog and News'), ('above_footer_blog_news', 'Above Footer Blog and News')], help_text='Where the ad will appear', max_length=50, unique=True)),
                ('desktop_image', models.ImageField(blank=True, help_text='Image for desktop view', null=True, upload_to='ads/desktop/')),
                ('mobile_image', models.ImageField(blank=True, help_text='Image for mobile view', null=True, upload_to='ads/mobile/')),
                ('redirect_url', models.URLField(blank=True, help_text='URL to redirect when the ad is clicked', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Control whether the ad is active or not')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
            },
        ),
    ]
