# Generated by Django 5.1.6 on 2025-03-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='placement',
            field=models.CharField(choices=[('roadblock_ad', 'Roadblock Ad All Pages'), ('exclusive_below_navbar', 'Exclusive Ad Below Navbar'), ('exclusive_above_footer', 'Exclusive Ad Above Footer'), ('below_navbar_blog_news', 'Below Navbar Blog and News'), ('above_headline_blog_news', 'Above Headline Blog and News'), ('below_headline_blog_news', 'Below Headline Blog and News'), ('below_featured_image_blog_news', 'Below Featured Image Blog and News'), ('above_footer_blog_news', 'Above Footer Blog and News')], help_text='Where the ad will appear', max_length=50, unique=True),
        ),
    ]
