# Generated by Django 5.1.6 on 2025-03-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='priority',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Lower the number, higher the priority', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
