# Generated by Django 5.1.6 on 2025-03-09 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0003_alter_consultancy_priority'),
        ('event', '0003_remove_event_organizer_event_organizer_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer_content_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer_object_id',
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultancy.consultancy'),
        ),
    ]
