# Generated by Django 5.1.5 on 2025-04-01 05:38

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('by', models.CharField(help_text='Name of the university or institution offering the scholarship', max_length=255)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='scholarship/images/')),
                ('detail', tinymce.models.HTMLField(blank=True, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('active_from', models.DateField(blank=True, null=True)),
                ('active_to', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('study_level', models.CharField(blank=True, choices=[('bachelors', "Bachelor's"), ('masters', "Master's"), ('phd', 'PhD'), ('diploma', 'Diploma')], max_length=20, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_items', to='destination.destination')),
            ],
        ),
    ]
