# Generated by Django 5.1.6 on 2025-03-26 07:57

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover_images/')),
                ('fee', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.PositiveIntegerField(blank=True, default=None, help_text='Lower the number, higher the priority', null=True)),
                ('short_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('eligibility', tinymce.models.HTMLField(blank=True, null=True)),
                ('course_structure', tinymce.models.HTMLField(blank=True, null=True)),
                ('job_prospects', tinymce.models.HTMLField(blank=True, null=True)),
                ('scholarship', tinymce.models.HTMLField(blank=True, null=True)),
                ('features', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
    ]
