# Generated by Django 5.1.6 on 2025-03-05 08:12

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover_images/')),
                ('fee', models.CharField(blank=True, max_length=100, null=True)),
                ('short_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('eligibility', tinymce.models.HTMLField(blank=True, null=True)),
                ('course_structure', tinymce.models.HTMLField(blank=True, null=True)),
                ('job_prospects', tinymce.models.HTMLField(blank=True, null=True)),
                ('scholarship', tinymce.models.HTMLField(blank=True, null=True)),
                ('features', tinymce.models.HTMLField(blank=True, null=True)),
                ('duration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.courseduration')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_list', to='university.university')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
