# Generated by Django 5.1.6 on 2025-03-26 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('course', '0001_initial'),
        ('destination', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='destination.destination'),
        ),
        migrations.AddField(
            model_name='course',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='courses', to='core.discipline'),
        ),
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_courses', to='university.university'),
        ),
    ]
