# Generated by Django 5.1.6 on 2025-03-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_discipline'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='courses', to='core.discipline'),
        ),
    ]
