# Generated by Django 5.1.6 on 2025-04-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='entry_score',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='next_intake',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
