# Generated by Django 5.1.6 on 2025-03-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_disciplines'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='priority',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Lower the number, higher the priority', null=True),
        ),
    ]
