# Generated by Django 5.1.6 on 2025-03-08 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_priority'),
        ('destination', '0002_destination_consultancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='destination.destination'),
        ),
    ]
