# Generated by Django 5.1.5 on 2025-03-12 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_destination'),
        ('university', '0004_alter_university_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_courses', to='university.university'),
        ),
    ]
