# Generated by Django 5.1.6 on 2025-03-09 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='published_date',
            new_name='date',
        ),
    ]
