# Generated by Django 5.1.6 on 2025-05-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='faqs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
