# Generated by Django 5.1.6 on 2025-03-06 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_verifieditem'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='university',
            name='verified',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.verifieditem'),
        ),
    ]
