# Generated by Django 5.1.6 on 2025-03-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_discipline'),
        ('university', '0002_university_consultancies_to_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='universities', to='core.discipline'),
        ),
    ]
