# Generated by Django 5.1.5 on 2025-03-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_university_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='qs_world_ranking',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
